aursec-init: check if connected with blockchain

diff --git a/aursec/bin/aursec-init b/aursec/bin/aursec-init
--- a/aursec/bin/aursec-init
+++ b/aursec/bin/aursec-init
@@ -74,6 +74,12 @@ function init(){
 	((verbose))&& echo "$tmp" >&2
 	tmp=$(aursec-chain -v -d mine blocks 2 2>&1)
 	((verbose))&& echo "$tmp" >&2
+	if [[ $(aursec-chain get-hash "hello world") == "it works"* ]]; then
+		echo "Error: couldn't synchronize with the network" >&2
+		tmp=$(systemctl stop aursec-blockchain.service 2>&1)
+		((verbose))&& echo "$tmp" >&2
+		exit 3
+	fi
 	tmp=$(systemctl stop aursec-blockchain.service 2>&1)
 	((verbose))&& echo "$tmp" >&2
 
