aursec-init & chain: add max times for curl and wait for sync

diff --git a/aursec/bin/aursec-chain b/aursec/bin/aursec-chain
--- a/aursec/bin/aursec-chain
+++ b/aursec/bin/aursec-chain
@@ -30,24 +30,24 @@ colorize
 
 # shows usage
 function usage() {
-	plain "Usage: $0 [-h|--help] [-v|--verbose] ..." >&2
+    plain "Usage: $0 [-h|--help] [-v|--verbose] ..." >&2
 }
 
 #shows help
 function help() {
-	usage
-	cat >&2 <<EOF
+        usage
+        cat >&2 <<EOF
 Bash API for the Ethereum-Blockchain of aursec
 
 Options:
   -h, --help         Shows this help message
   -v, --verbose      Shows additional output
-  -d, --debug		 Shows debug output
-  mine 	start 		 Starts mining with the coinbase account
-  		stop 		 Stops mining with the coinbase account
-  		auto         Auto-mine. This exists for the systemd timer
-  		blocks N 	 mines min. N Blocks with the coinbase account
-  get-hash 	ID 		 Gets current consensus-hash of package ID
+  -d, --debug            Shows debug output
+  mine  start            Starts mining with the coinbase account
+        stop             Stops mining with the coinbase account
+        auto         Auto-mine. This exists for the systemd timer
+        blocks N         mines min. N Blocks with the coinbase account
+  get-hash      ID               Gets current consensus-hash of package ID
   commit-hash ID HA  Commits new hash HA of package ID in the blockchain
 
 Copying:
@@ -59,197 +59,197 @@ EOF
 
 # trap ... for errorhandling
 error() {
-  	local parent_lineno="$1"
-  	local message="$2"
-  	local code="${3:-1}"
-  	if ((debug)); then
-  		if [[ -n "$message" ]] ; then
-	    	echo "aursec-chain: Error on or near line ${parent_lineno}: ${message}; use verbose to get more details; exiting with status ${code}" >&2
-	  	else
-	    	echo "aursec-chain: Error on or near line ${parent_lineno}; use verbose to get more details; exiting with status ${code}" >&2
-	  	fi
-  	else
-		echo "aursec-chain: error. For further details activate verbose and debug" >&2
-	fi
+    local parent_lineno="$1"
+    local message="$2"
+    local code="${3:-1}"
+    if ((debug)); then
+        if [[ -n "$message" ]] ; then
+        echo "aursec-chain: Error on or near line ${parent_lineno}: ${message}; use verbose to get more details; exiting with status ${code}" >&2
+        else
+        echo "aursec-chain: Error on or near line ${parent_lineno}; use verbose to get more details; exiting with status ${code}" >&2
+        fi
+    else
+        echo "aursec-chain: error. For further details activate verbose and debug" >&2
+    fi
   exit "${code}"
 }
 
 # Checks if the
 function is_mining(){
-	trap 'error ${LINENO}' ERR
-	((verbose)) && echo "Checking if already mining" >&2
-	if curl localhost:${PORT} ${silence} -X POST --data '{"jsonrpc":"2.0", "method":"eth_mining", "params":[], "id":1}' | grep -q 'true'; then
-		((verbose)) && echo "Is mining" >&2
-		echo 1
-	else
-		((verbose)) && echo "Is not mining" >&2
-		echo 0
-	fi
+    trap 'error ${LINENO}' ERR
+    ((verbose)) && echo "Checking if already mining" >&2
+    if curl localhost:${PORT} ${silence} -X POST --data '{"jsonrpc":"2.0", "method":"eth_mining", "params":[], "id":1}' | grep -q 'true'; then
+        ((verbose)) && echo "Is mining" >&2
+        echo 1
+    else
+        ((verbose)) && echo "Is not mining" >&2
+        echo 0
+    fi
 }
 
 # Starts mining via RPC if not already mining
 # TO DO: Issue 4 Laptop Battery
 function start_mining() {
-	trap 'error ${LINENO}' ERR
-	declare tmp
-	#local cpu_level
-	#if acpi -a | grep -q 'on-line'; then
-	#	cpu_level=5
-	#else
-	#	cpu_level=+15
-	#fi
-	if [[ "$(is_mining)" -eq "0" ]]; then
-		((verbose)) && echo "Starting mining" >&2
-		tmp=$(curl localhost:${PORT} ${silence} -X POST --data '{"jsonrpc":"2.0", "method":"miner_start", "params":[], "id":1}')
-		((verbose)) && echo "$tmp" >&2
-		touch $MARKER_FOLDER/last-mine.marker
-	fi
-	#for pid in `pgrep -f "geth.*--datadir $BLOCKCHAIN_PATH"`; do
-	#	renice -n ${cpu_level} -p $pid &
-	#done
+    trap 'error ${LINENO}' ERR
+    declare tmp
+    #local cpu_level
+    #if acpi -a | grep -q 'on-line'; then
+    #       cpu_level=5
+    #else
+    #       cpu_level=+15
+    #fi
+    if [[ "$(is_mining)" -eq "0" ]]; then
+        ((verbose)) && echo "Starting mining" >&2
+        tmp=$(curl localhost:${PORT} ${silence} -m 30 -X POST --data '{"jsonrpc":"2.0", "method":"miner_start", "params":[], "id":1}')
+        ((verbose)) && echo "$tmp" >&2
+        touch $MARKER_FOLDER/last-mine.marker
+    fi
+    #for pid in `pgrep -f "geth.*--datadir $BLOCKCHAIN_PATH"`; do
+    #       renice -n ${cpu_level} -p $pid &
+    #done
 
-	echo "$tmp" >/dev/null
+    echo "$tmp" >/dev/null
 }
 
 # Stops mining via RPC
 function stop_mining() {
-	trap 'error ${LINENO}' ERR
-	declare tmp
-	((verbose)) && echo "Stopping mining" >&2
-	while [[ "$(is_mining)" -eq "1" ]]; do
-		tmp=$(curl localhost:${PORT} ${silence} -X POST --data '{"jsonrpc":"2.0", "method":"miner_stop", "params":[], "id":1}')
-	done
-	((verbose)) && echo "$tmp" >&2
-	echo "$tmp" >/dev/null
+    trap 'error ${LINENO}' ERR
+    declare tmp
+    ((verbose)) && echo "Stopping mining" >&2
+    while [[ "$(is_mining)" -eq "1" ]]; do
+            tmp=$(curl localhost:${PORT} ${silence} -m 30 -X POST --data '{"jsonrpc":"2.0", "method":"miner_stop", "params":[], "id":1}')
+    done
+    ((verbose)) && echo "$tmp" >&2
+    echo "$tmp" >/dev/null
 }
 
 # Returns Dec number of current block
 function get_current_block() {
-	trap 'error ${LINENO}' ERR
-	declare block_hexnum
-	((verbose)) && echo "Getting current block" >&2
-	block_hexnum=$(curl localhost:${PORT} ${silence} -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber", "id":1}' | grep -oP '(?<="result".")\w+')
-	printf "%d\n" "$block_hexnum"
+    trap 'error ${LINENO}' ERR
+    declare block_hexnum
+    ((verbose)) && echo "Getting current block" >&2
+    block_hexnum=$(curl localhost:${PORT} ${silence} -m 30 -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber", "id":1}' | grep -oP '(?<="result".")\w+')
+    printf "%d\n" "$block_hexnum"
 }
 
 # Mines min. N blocks
 # $1 = N
 function mine_n_blocks() {
-	trap 'error ${LINENO}' ERR
-	declare start_block
-	((verbose)) && echo "Starting mining $1 blocks" >&2
-	if ! [[ $1 =~ ^[0-9]+$ ]] ; then
-		echo "error: 3rd argument ($1) is no number"
-		exit 1
-	fi
+    trap 'error ${LINENO}' ERR
+    declare start_block
+    ((verbose)) && echo "Starting mining $1 blocks" >&2
+    if ! [[ $1 =~ ^[0-9]+$ ]] ; then
+        echo "error: 3rd argument ($1) is no number"
+        exit 1
+    fi
 
-	((verbose)) && echo "Waiting till no other job is mining" >&2
-	while [[ "$(is_mining)" -eq "1" ]]; do
-		sleep 0.5
-	done
-	start_block=$(get_current_block)
-	start_mining
-	# waiting till N blocks were mined
-	while [[ $(get_current_block) < $((start_block + $1)) ]]; do
-		if [[ "$(is_mining)" -eq "0" ]]; then
-			echo "Something stoped mining" >&2
-			exit 1
-		fi
-		sleep 0.2
-	done
-	stop_mining
+    ((verbose)) && echo "Waiting till no other job is mining" >&2
+    while [[ "$(is_mining)" -eq "1" ]]; do
+        sleep 0.5
+    done
+    start_block=$(get_current_block)
+    start_mining
+    # waiting till N blocks were mined
+    while [[ $(get_current_block) < $((start_block + $1)) ]]; do
+        if [[ "$(is_mining)" -eq "0" ]]; then
+            echo "Something stoped mining" >&2
+            exit 1
+        fi
+        sleep 0.2
+    done
+    stop_mining
 }
 
 function mine_auto() {
-	if [[ $(whoami) != aursec ]]; then
-		echo "Auto-mining must be done as 'aursec'!" >&2
-		exit 1
-	fi
+    if [[ $(whoami) != aursec ]]; then
+        echo "Auto-mining must be done as 'aursec'!" >&2
+        exit 1
+    fi
 
-	# if the last commit was after the last mine
-	if [[ $MARKER_FOLDER/last-commit.marker -nt $MARKER_FOLDER/last-mine.marker ]]; then
-		echo "Committed since the last mine, mining more." >&2
-		mine_n_blocks 4
-	else
-		echo "No commits since the last mine, mining one block only." >&2
-		mine_n_blocks 1
-	fi
+    # if the last commit was after the last mine
+    if [[ $MARKER_FOLDER/last-commit.marker -nt $MARKER_FOLDER/last-mine.marker ]]; then
+        echo "Committed since the last mine, mining more." >&2
+        mine_n_blocks 4
+    else
+        echo "No commits since the last mine, mining one block only." >&2
+        mine_n_blocks 1
+    fi
 }
 
 # Commits Hash into the blockchain
 # $1 = ID
 # $2 = HASH
 function commit_hash() {
-	trap 'error ${LINENO}' ERR
-	declare tmp offset1 offset2 offset2_dec offset2_hex coinbase string1 string2
-	((verbose)) && echo "Committing Hash $2 of Package $1" >&2
-	((verbose)) && echo "Parsing input to json" >&2
-	offset1=$(hex_to_pre_hex32 40)
-	string1=$(string_to_hex "$1")
-	string2=$(string_to_hex "$2")
-	offset2_dec=$((${#string1}/2+64))
-	offset2_hex=$(echo "obase=16; $offset2_dec" | bc)
-	offset2=$(hex_to_pre_hex32 "$offset2_hex")
-	((verbose)) && echo "Getting coinbase" >&2
-	coinbase=$(curl localhost:${PORT} ${silence} -X POST --data '{"jsonrpc":"2.0","method":"eth_coinbase", "id":1}' | grep -oP '(?<="result".")\w+')
-	((verbose)) && echo "Sending transaction" >&2
-	tmp=$(curl localhost:${PORT} ${silence} -X POST --data '{"jsonrpc":"2.0","id":"1","method":"eth_sendTransaction","params":[{"data": "'$COMMIT_HASH_ADDR_HEX$offset1$offset2$string1$string2'","from":"'$coinbase'","gasPrice":"'$GAS_PRICE'","to":"'$CONTRACT_ADDR_HEX'", "gas":"'$GAS'"}]}')
-	((verbose)) && echo "$tmp" >&2
-	echo "$tmp" >/dev/null
-	touch $MARKER_FOLDER/last-commit.marker
+    trap 'error ${LINENO}' ERR
+    declare tmp offset1 offset2 offset2_dec offset2_hex coinbase string1 string2
+    ((verbose)) && echo "Committing Hash $2 of Package $1" >&2
+    ((verbose)) && echo "Parsing input to json" >&2
+    offset1=$(hex_to_pre_hex32 40)
+    string1=$(string_to_hex "$1")
+    string2=$(string_to_hex "$2")
+    offset2_dec=$((${#string1}/2+64))
+    offset2_hex=$(echo "obase=16; $offset2_dec" | bc)
+    offset2=$(hex_to_pre_hex32 "$offset2_hex")
+    ((verbose)) && echo "Getting coinbase" >&2
+    coinbase=$(curl localhost:${PORT} ${silence} -m 30 -X POST --data '{"jsonrpc":"2.0","method":"eth_coinbase", "id":1}' | grep -oP '(?<="result".")\w+')
+    ((verbose)) && echo "Sending transaction" >&2
+    tmp=$(curl localhost:${PORT} ${silence} -m 30 -X POST --data '{"jsonrpc":"2.0","id":"1","method":"eth_sendTransaction","params":[{"data": "'$COMMIT_HASH_ADDR_HEX$offset1$offset2$string1$string2'","from":"'$coinbase'","gasPrice":"'$GAS_PRICE'","to":"'$CONTRACT_ADDR_HEX'", "gas":"'$GAS'"}]}')
+    ((verbose)) && echo "$tmp" >&2
+    echo "$tmp" >/dev/null
+    touch $MARKER_FOLDER/last-commit.marker
 }
 
 # Get Hash (+times submitted) for an ID
 # $1 = ID
 function get_hash() {
-	trap 'error ${LINENO}' ERR
-	declare offset string coinbase hex_result
-	((verbose)) && echo "Getting hash of package $ID" >&2
-	((verbose)) && echo "Parsing input to json" >&2
-	offset=$(hex_to_pre_hex32 20)
-	string=$(string_to_hex "$1")
-	((verbose)) && echo "get coinbase" >&2
-	coinbase=$(curl localhost:${PORT} ${silence} -X POST --data '{"jsonrpc":"2.0","method":"eth_coinbase", "id":1}'  | grep -oP '(?<="result".")\w+')
-	((verbose)) && echo "send call" >&2
-	hex_result=$(curl localhost:${PORT} ${silence} -X POST --data '{"jsonrpc":"2.0", "method":"eth_call", "params":[{"from": "'$coinbase'", "to": "'$CONTRACT_ADDR_HEX'", "data": "'$GET_HASH_ADDR_HEX$offset$string'"},"latest"], "id":1}' |grep -oP '(?<="result"."0x)\w+')
-	if [ ${#hex_result} -le 0 ]; then
-		echo "Error: Connection Failed" >&2
-		exit 1
-	fi
-	if [ ${#hex_result} -le 192 ]; then
-		echo null 0
-	else
-		declare num_of_commits_dec hash_size_dec hash_printable hash_
-		((verbose)) && echo "Parsing result to strings" >&2
+    trap 'error ${LINENO}' ERR
+    declare offset string coinbase hex_result
+    ((verbose)) && echo "Getting hash of package $ID" >&2
+    ((verbose)) && echo "Parsing input to json" >&2
+    offset=$(hex_to_pre_hex32 20)
+    string=$(string_to_hex "$1")
+    ((verbose)) && echo "get coinbase" >&2
+    coinbase=$(curl localhost:${PORT} ${silence} -m 30 -X POST --data '{"jsonrpc":"2.0","method":"eth_coinbase", "id":1}'  | grep -oP '(?<="result".")\w+')
+    ((verbose)) && echo "send call" >&2
+    hex_result=$(curl localhost:${PORT} ${silence} -m 30 -X POST --data '{"jsonrpc":"2.0", "method":"eth_call", "params":[{"from": "'$coinbase'", "to": "'$CONTRACT_ADDR_HEX'", "data": "'$GET_HASH_ADDR_HEX$offset$string'"},"latest"], "id":1}' |grep -oP '(?<="result"."0x)\w+')
+    if [ ${#hex_result} -le 0 ]; then
+        echo "Error: Connection Failed" >&2
+        exit 1
+    fi
+    if [ ${#hex_result} -le 192 ]; then
+        echo null 0
+    else
+        declare num_of_commits_dec hash_size_dec hash_printable hash_
+        ((verbose)) && echo "Parsing result to strings" >&2
 
-		num_of_commits_dec=$(printf "%d\n" "$(cut -c65-128 <<< "$hex_result")")
-		hash_size_dec=$((($(cut -c129-192 <<< "$hex_result" | sed 's/^0*//')-1)*2))
-		hash_printable=$(sed 's/.\{2\}/\\x&/g' <<< "$(cut -c193-$((193+hash_size_dec-1)) <<< "$hex_result")")
-		hash_=$(echo -e "$hash_printable")
+        num_of_commits_dec=$(printf "%d\n" "$(cut -c65-128 <<< "$hex_result")")
+        hash_size_dec=$((($(cut -c129-192 <<< "$hex_result" | sed 's/^0*//')-1)*2))
+        hash_printable=$(sed 's/.\{2\}/\\x&/g' <<< "$(cut -c193-$((193+hash_size_dec-1)) <<< "$hex_result")")
+        hash_=$(echo -e "$hash_printable")
 
-		echo "$hash_ $num_of_commits_dec"
-	fi
-	echo "$tmp" >/dev/null
+        echo "$hash_ $num_of_commits_dec"
+    fi
+    echo "$tmp" >/dev/null
 }
 
 # convert String to hex-string (Ethereum ABI-style)
 # $1 = String
 function string_to_hex() {
-	declare hexstring
-	hexstring=$(xxd -pu <<< "$1" | sed ':a;N;$!ba;s/[[:space:]]//g')
-	echo "$(hex_to_pre_hex32 "$((${#hexstring}/2))")$(hex_to_post_hex32 "$hexstring")"
+    declare hexstring
+    hexstring=$(xxd -pu <<< "$1" | sed ':a;N;$!ba;s/[[:space:]]//g')
+    echo "$(hex_to_pre_hex32 "$((${#hexstring}/2))")$(hex_to_post_hex32 "$hexstring")"
 }
 
 # converts hex-String to hexstring with length%32byte==0 the prestring is filled with 0s
 # $1 = input hexstring
 function hex_to_pre_hex32() {
-	echo "$(printf "%$((64-${#1}%64))s" | tr " " "0")$1"
+    echo "$(printf "%$((64-${#1}%64))s" | tr " " "0")$1"
 }
 
 # converts hex-String to hexstring with length%32byte==0 the poststring is filled with 0s
 # $1 = input hexstring
 function hex_to_post_hex32() {
-	echo "$1$(printf "%$((64-${#1}%64))s" | tr " " "0")"
+        echo "$1$(printf "%$((64-${#1}%64))s" | tr " " "0")"
 }
 
 # Parse the arguments
@@ -259,14 +259,14 @@ silence='-s'
 while true; do
     case "$1" in
         -v|--verbose)
-			verbose=1
-			silence=''
-			shift
-			;;
-		-d|--debug)
-			debug=1
-			shift
-			;;
+            verbose=1
+            silence=''
+            shift
+            ;;
+        -d|--debug)
+            debug=1
+            shift
+            ;;
         -h|--help)
             help
             exit 0 ;;
@@ -277,21 +277,21 @@ done
 # main
 case "$1" in
     mine)
-		case "$2" in
-			start)
-				start_mining ;;
-			stop)
-				stop_mining ;;
-			auto)
-				mine_auto ;;
-			blocks)
-				mine_n_blocks "$3";;
-			*) usage;;
-		esac ;;
+        case "$2" in
+            start)
+                start_mining ;;
+            stop)
+                stop_mining ;;
+            auto)
+                mine_auto ;;
+            blocks)
+                mine_n_blocks "$3";;
+            *) usage;;
+        esac ;;
     commit-hash)
-		commit_hash "$2" "$3";;
-	get-hash)
-		get_hash "$2";;
+        commit_hash "$2" "$3";;
+    get-hash)
+        get_hash "$2";;
     *) usage ;;
 esac
 exit 0
diff --git a/aursec/bin/aursec-init b/aursec/bin/aursec-init
--- a/aursec/bin/aursec-init
+++ b/aursec/bin/aursec-init
@@ -11,12 +11,12 @@ GENESIS_BLOCK="/usr/share/aursec/genesis_block.json"
 PORT="8105"
 
 function usage() {
-	plain "Usage: $0 [-h|--help]" >&2
+    plain "Usage: $0 [-h|--help]" >&2
 }
 
 function help() {
-	usage
-	cat >&2 <<EOF
+    usage
+    cat >&2 <<EOF
 Initialize a Ethereum Blockchain and generates a new account.
 
 Options:
@@ -30,63 +30,96 @@ Copying:
 EOF
 }
 
+# trap ... for errorhandling
+error() {
+    local parent_lineno="$1"
+    local message="$2"
+    local code="${3:-1}"
+    if ((debug)); then
+        if [[ -n "$message" ]] ; then
+        echo "aursec-chain: Error on or near line ${parent_lineno}: ${message}; use verbose to get more details; exiting with status ${code}" >&2
+        else
+        echo "aursec-chain: Error on or near line ${parent_lineno}; use verbose to get more details; exiting with status ${code}" >&2
+        fi
+    else
+        echo "aursec-chain: error. For further details activate verbose and debug" >&2
+    fi
+  exit "${code}"
+}
+
+# Returns Dec number of current block
+function get_current_block() {
+    trap 'error ${LINENO}' ERR
+    declare block_hexnum
+    ((verbose)) && echo "Getting current block" >&2
+    block_hexnum=$(curl localhost:${PORT} "${silence}" -m 30 -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber", "id":1}' | grep -oP '(?<="result".")\w+')
+    printf "%d\n" "$block_hexnum"
+}
+
 # Creates blockchain and account
 function init(){
-	declare tmp
-	((verbose)) && echo "Creating directory." >&2
-	mkdir -p $BLOCKCHAIN_PATH
+    trap 'error ${LINENO}' ERR
+    declare tmp
+    ((verbose)) && echo "Creating directory." >&2
+    mkdir -p $BLOCKCHAIN_PATH
 
-	mkdir $BLOCKCHAIN_PATH/markers
-	touch $BLOCKCHAIN_PATH/markers/{last-commit.marker,last-mine.marker}
+    mkdir $BLOCKCHAIN_PATH/markers
+    touch $BLOCKCHAIN_PATH/markers/{last-commit.marker,last-mine.marker}
 
-	chmod -R 755 $BLOCKCHAIN_PATH
-	chmod 666 $BLOCKCHAIN_PATH/markers/last-commit.marker
-	chmod 666 $BLOCKCHAIN_PATH/markers/last-mine.marker
-	chown -R aursec:aursec $BLOCKCHAIN_PATH
+    chmod -R 755 $BLOCKCHAIN_PATH
+    chmod 666 $BLOCKCHAIN_PATH/markers/last-commit.marker
+    chmod 666 $BLOCKCHAIN_PATH/markers/last-mine.marker
+    chown -R aursec:aursec $BLOCKCHAIN_PATH
 
-	# check if genesis block exists
-	((verbose)) && echo "Looking for genesis block" >&2
-	if [ ! -e "$GENESIS_BLOCK" ]; then
-		echo "The genesis block does not exist" >&2
-		exit 3
-	fi
-	# init blockchain
-	((verbose)) && echo "Creating Blockchain." >&2
-	tmp=$(su aursec -c "geth --datadir $BLOCKCHAIN_PATH/chain init $GENESIS_BLOCK "  2>&1)
-	((verbose))&& echo "$tmp" >&2
-	# generate password
-	((verbose)) && echo "Generating random password." >&2
-	tmp=$(su aursec -c "dd if=/dev/urandom count=20 | sha256sum | base64 | head -c 32 > ${BLOCKCHAIN_PATH}/password " 2>&1)
-	((verbose))&& echo "$tmp" >&2
-	# new blockchain account
-	((verbose)) && echo "Creating new account." >&2
-	tmp=$(su aursec -c "geth --password ${BLOCKCHAIN_PATH}/password --datadir $BLOCKCHAIN_PATH/chain account new " 2>&1)
-	((verbose))&& echo "$tmp" >&2
+    # check if genesis block exists
+    ((verbose)) && echo "Looking for genesis block" >&2
+    if [ ! -e "$GENESIS_BLOCK" ]; then
+        echo "The genesis block does not exist" >&2
+        exit 3
+    fi
+    # init blockchain
+    ((verbose)) && echo "Creating Blockchain." >&2
+    tmp=$(su aursec -c "geth --datadir $BLOCKCHAIN_PATH/chain init $GENESIS_BLOCK "  2>&1)
+    ((verbose))&& echo "$tmp" >&2
+    # generate password
+    ((verbose)) && echo "Generating random password." >&2
+    tmp=$(su aursec -c "dd if=/dev/urandom count=20 | sha256sum | base64 | head -c 32 > ${BLOCKCHAIN_PATH}/password " 2>&1)
+    ((verbose))&& echo "$tmp" >&2
+    # new blockchain account
+    ((verbose)) && echo "Creating new account." >&2
+    tmp=$(su aursec -c "geth --password ${BLOCKCHAIN_PATH}/password --datadir $BLOCKCHAIN_PATH/chain account new " 2>&1)
+    ((verbose))&& echo "$tmp" >&2
 
-	# Give everything except for the markers folder mode 700
-	find $BLOCKCHAIN_PATH -maxdepth 1 -mindepth 1 -not -name '*markers*' -not -name '.' -exec chmod -R 700 '{}' \;
+    # Give everything except for the markers folder mode 700
+    find $BLOCKCHAIN_PATH -maxdepth 1 -mindepth 1 -not -name '*markers*' -not -name '.' -exec chmod -R 700 '{}' \;
 
-	# Generate DAG
-	((verbose)) && echo "Creating DAG." >&2
-	tmp=$(su aursec -c "mkdir ${BLOCKCHAIN_PATH}/.ethash")
-	((verbose))&& echo "$tmp" >&2
-	su aursec -c "geth makedag 360000 ${BLOCKCHAIN_PATH}/.ethash" 2>&1
-	tmp=$(systemctl start aursec-blockchain.service 2>&1)
-	((verbose))&& echo "$tmp" >&2
-	sleep 15
-	while ! curl localhost:${PORT} "${silence}" -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' | grep -q false; do
-		sleep 1
-	done
-	tmp=$(aursec-chain -v -d mine blocks 2 2>&1)
-	((verbose))&& echo "$tmp" >&2
-	if [[ $(aursec-chain get-hash "hello world" 2>&1) != "it works"* ]]; then
-		echo "Error: couldn't synchronize with the network" >&2
-		tmp=$(systemctl stop aursec-blockchain.service 2>&1)
-		((verbose))&& echo "$tmp" >&2
-		exit 3
-	fi
-	tmp=$(systemctl stop aursec-blockchain.service 2>&1)
-	((verbose))&& echo "$tmp" >&2
+    # Generate DAG
+    ((verbose)) && echo "Creating DAG." >&2
+    tmp=$(su aursec -c "mkdir ${BLOCKCHAIN_PATH}/.ethash")
+    ((verbose))&& echo "$tmp" >&2
+    su aursec -c "geth makedag 360000 ${BLOCKCHAIN_PATH}/.ethash" 2>&1
+    tmp=$(systemctl start aursec-blockchain.service 2>&1)
+    ((verbose))&& echo "$tmp" >&2
+    sleep 15
+    ((verbose))&& echo "wait for first block" >&2
+    while [[ $(get_current_block) -le 5 ]]; do 
+    	sleep 15
+    done 
+    sleep 15
+    ((verbose))&& echo "synched" >&2
+    ((verbose))&& echo "$tmp" >&2
+    if [[ $(aursec-chain get-hash "hello world" 2>&1) != "it works"* ]]; then
+        echo "Error: couldn't synchronize with the network" >&2
+        tmp=$(systemctl stop aursec-blockchain.service 2>&1)
+        ((verbose))&& echo "$tmp" >&2
+        exit 3
+    fi
+    ((verbose))&& echo "got hash" >&2
+    tmp=$(aursec-chain -v -d mine blocks 2 2>&1)
+    ((verbose))&& echo "$tmp" >&2
+    ((verbose))&& echo "mined blocks" >&2
+    tmp=$(systemctl stop aursec-blockchain.service 2>&1)
+    ((verbose))&& echo "$tmp" >&2
 
 }
 
@@ -97,10 +130,11 @@ silence='-s'
 while true; do
     case "$1" in
         -v|--verbose)
-			verbose=1
-			silence=''
-			shift
-			;;
+            verbose=1
+            debug=1
+            silence=''
+            shift
+            ;;
         -h|--help)
             help
             exit 0 ;;
@@ -109,25 +143,25 @@ while true; do
 done
 
 if [ "$EUID" -ne 0 ]; then
-	echo "Please run this script as root."
-	exit 2
+    echo "Please run this script as root."
+    exit 2
 fi
 
 ((verbose)) && echo "Checking if $BLOCKCHAIN_PATH already exists."
 
 if [ -d $BLOCKCHAIN_PATH ]; then
-	read -rp "The Path $BLOCKCHAIN_PATH already exists. Do you want to delete all existing Files in this Folder? [y/N]" yn
-	case $yn in
-		y|Y )
-			rm -rf $BLOCKCHAIN_PATH
-			init;;
-		* )
-			echo "Canceled the blockchain initialization."
-			exit 1
-	esac
+    read -rp "The Path $BLOCKCHAIN_PATH already exists. Do you want to delete all existing Files in this Folder? [y/N]" yn
+    case $yn in
+        y|Y )
+	        rm -rf $BLOCKCHAIN_PATH
+    	    init;;
+        * )
+       	 	echo "Canceled the blockchain initialization."
+        	exit 1
+    esac
 
 else
-	init
+    init
 fi
 echo "Initialization of the blockchain was successful. Please start the systemd service. The following synchronisation will take a while."
 exit 0
