Improved English in aursec-chain closes #11

diff --git a/aursec/bin/aursec-chain b/aursec/bin/aursec-chain
--- a/aursec/bin/aursec-chain
+++ b/aursec/bin/aursec-chain
@@ -58,10 +58,10 @@ EOF
 function is_mining(){
 	((verbose))&& echo "Checking if already mining" >&2
 	if curl localhost:$PORT "$silence" -X POST --data '{"jsonrpc":"2.0", "method":"eth_mining", "params":[], "id":1}' | grep -q 'true'; then
-		((verbose))&& echo "is mining" >&2
+		((verbose))&& echo "Is mining" >&2
 		echo 1
 	else
-		((verbose))&& echo "is not mining" >&2
+		((verbose))&& echo "Is not mining" >&2
 		echo 0
 	fi
 
@@ -78,7 +78,7 @@ function start_mining() {
 	#	cpu_level=+15
 	#fi
 	if [[ "$(is_mining)" -eq "0" ]]; then
-		((verbose))&& echo "start mining" >&2
+		((verbose))&& echo "Starting mining" >&2
 		tmp=$(curl localhost:$PORT "$silence" -X POST --data '{"jsonrpc":"2.0", "method":"miner_start", "params":[], "id":1}')
 		((verbose))&& echo "$tmp" >&2
 	fi
@@ -90,7 +90,7 @@ function start_mining() {
 # Stops mining via RPC
 function stop_mining() {
 	declare tmp
-	((verbose))&& echo "stop mining" >&2
+	((verbose))&& echo "Stopping mining" >&2
 	tmp=$(curl localhost:$PORT "$silence" -X POST --data '{"jsonrpc":"2.0", "method":"miner_stop", "params":[], "id":1}')
 	((verbose))&& echo "$tmp" >&2
 }
@@ -98,7 +98,7 @@ function stop_mining() {
 # Returns Dec number of current block
 function get_current_block() {
 	declare block_hexnum
-	((verbose)) && echo "get current block" >&2
+	((verbose)) && echo "Getting current block" >&2
 	block_hexnum=$(curl "$silence" --data '{"jsonrpc":"2.0","method":"eth_blockNumber", "id":1}' localhost:$PORT | grep -oP '(?<="result".")\w+') 
 	printf "%d\n" "$block_hexnum"
 }
@@ -107,9 +107,9 @@ function get_current_block() {
 # $1 = N
 function mine_n_blocks() {
 	declare start_block 
-	((verbose))&& echo "start mining $1 blocks" >&2
+	((verbose))&& echo "Starting mining $1 blocks" >&2
 	if ! [[ $1 =~ ^[0-9]+$ ]] ; then
-		echo "error: 3rd argument ($1) no number"
+		echo "error: 3rd argument ($1) is no number"
 		exit 1
 	fi
 	start_block=$(get_current_block)
@@ -126,20 +126,20 @@ function mine_n_blocks() {
 # $2 = HASH
 function commit_hash() {
 	declare tmp offset1 offset2 offset2_dec offset2_hex coinbase string1 string2 
-	((verbose))&& echo "Commit Hash $2 of Package $1" >&2
-	((verbose))&& echo "parse input to json" >&2
+	((verbose))&& echo "Committing Hash $2 of Package $1" >&2
+	((verbose))&& echo "Parsing input to json" >&2
 	offset1=$(hex_to_pre_hex32 40)
 	string1=$(string_to_hex "$1")
 	string2=$(string_to_hex "$2")
 	offset2_dec=$((${#string1}/2+64))
 	offset2_hex=$(echo "obase=16; $offset2_dec" | bc)
 	offset2=$(hex_to_pre_hex32 "$offset2_hex")
-	((verbose))&& echo "get coinbase" >&2
+	((verbose))&& echo "Getting coinbase" >&2
 	coinbase=$(curl localhost:$PORT "$silence" --data '{"jsonrpc":"2.0","method":"eth_coinbase", "id":1}' | grep -oP '(?<="result".")\w+')
-	((verbose))&& echo "send Transaction" >&2
+	((verbose))&& echo "Sending transaction" >&2
 	tmp=$(curl localhost:$PORT "$silence" -X POST --data "{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"eth_sendTransaction\",\"params\":[{\"data\":\"$COMMIT_HASH_ADDR_HEX$offset1$offset2$string1$string2\",\"from\":\"$coinbase\",\"gasPrice\":\"$GAS_PRICE\",\"to\":\"$CONTRACT_ADDR_HEX\", \"gas\":\"$GAS\"}]}")
 	((verbose))&& echo "$tmp" >&2
-	((verbose))&& echo "mine blocks to verify transaction" >&2
+	((verbose))&& echo "Mining blocks to verify transaction" >&2
 	mine_n_blocks 3
 }
 
@@ -147,8 +147,8 @@ function commit_hash() {
 # $1 = ID
 function get_hash() {
 	declare offset string coinbase hex_result 
-	((verbose))&& echo "Get hash of package $ID" >&2
-	((verbose))&& echo "parse input to json" >&2
+	((verbose))&& echo "Getting hash of package $ID" >&2
+	((verbose))&& echo "Parsing input to json" >&2
 	offset=$(hex_to_pre_hex32 20)
 	string=$(string_to_hex "$1")
 	((verbose))&& echo "get coinbase" >&2
@@ -159,7 +159,7 @@ function get_hash() {
 		echo null 0
 	else
 		declare num_of_commits_hex num_of_commits_dec hash_halfsize_dec hash_size_dec hash_hex hash_printable hash
-		((verbose))&& echo "parse result to strings" >&2
+		((verbose))&& echo "Parsing result to strings" >&2
 		num_of_commits_hex=$(echo "$hex_result" | cut -c65-128)
 		num_of_commits_dec=$(printf "%d\n" "$num_of_commits_hex")
 		hash_halfsize_dec=$(echo "$hex_result" |cut -c129-192 | sed 's/^0*//')
